name: CI/CD Pipeline - Primeflow-Hub V8

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20.x'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job 1: Lint e Validação
  lint:
    name: Lint e Validação de Código
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci --legacy-peer-deps
      
      - name: Lint frontend
        run: npm run lint || true
      
      - name: TypeScript check
        run: npx tsc --noEmit || true
      
      - name: Lint backend
        run: |
          cd apps/api
          npm run lint || true
          cd ../..
      
      - name: Lint workers
        run: |
          cd apps/worker
          npm run lint || true
          cd ../..

  # Job 2: Testes Unitários
  test-unit:
    name: Testes Unitários
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci --legacy-peer-deps
      
      - name: Executar testes frontend
        run: npm test -- --coverage || true
      
      - name: Executar testes backend
        run: |
          cd apps/api
          npm test -- --coverage || true
          cd ../..
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests

  # Job 3: Testes de Integração
  test-integration:
    name: Testes de Integração
    runs-on: ubuntu-latest
    needs: test-unit
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: primeflow_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci --legacy-peer-deps
      
      - name: Executar migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/primeflow_test
        run: npx prisma migrate deploy
      
      - name: Executar testes de integração
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/primeflow_test
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: npm run test:integration || true

  # Job 4: Build
  build:
    name: Build da Aplicação
    runs-on: ubuntu-latest
    needs: [test-unit, test-integration]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci --legacy-peer-deps
      
      - name: Build frontend
        run: npm run build
      
      - name: Build backend
        run: |
          cd apps/api
          npm run build
          cd ../..
      
      - name: Build workers
        run: |
          cd apps/worker
          npm run build
          cd ../..
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            apps/api/dist/
            apps/worker/dist/

  # Job 5: Testes E2E
  test-e2e:
    name: Testes End-to-End
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci --legacy-peer-deps
      
      - name: Instalar Playwright
        run: npx playwright install --with-deps
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      
      - name: Executar testes E2E
        run: npm run test:e2e || true
      
      - name: Upload screenshots de falhas
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-screenshots
          path: test-results/

  # Job 6: Security Scan
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Run npm audit
        run: npm audit --audit-level=moderate || true
      
      - name: Run Snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # Job 7: Build Docker Image
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build, security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Job 8: Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [docker, test-e2e]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.primeflow.com
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Adicionar comandos de deploy aqui
          # Ex: kubectl apply -f k8s/staging/
          # Ex: ssh user@staging-server "cd /app && ./deploy.sh"

  # Job 9: Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [docker, test-e2e]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://primeflow.com
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Adicionar comandos de deploy aqui
          # Ex: kubectl apply -f k8s/production/
          # Ex: ssh user@prod-server "cd /app && ./deploy.sh"
      
      - name: Notify deployment
        if: success()
        run: |
          echo "Production deployment successful!"
          # Adicionar notificação (Slack, email, etc.)

  # Job 10: Smoke Tests (Produção)
  smoke-tests:
    name: Smoke Tests (Production)
    runs-on: ubuntu-latest
    needs: deploy-production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Health check
        run: |
          curl -f https://primeflow.com/api/health || exit 1
      
      - name: Basic functionality test
        run: |
          # Adicionar testes básicos de funcionalidade
          echo "Running smoke tests..."
