#!/bin/bash
# ============================================
# SETUP ENVIRONMENT VARIABLES
# Creates .env file using detected configuration
# ============================================

set -e

CONFIG_FILE="${1:-/tmp/server-config.json}"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ Configuration file not found: $CONFIG_FILE"
  exit 1
fi

echo "⚙️  Setting up environment variables..."
echo ""

# Load configuration
PORT=$(cat "$CONFIG_FILE" | jq -r '.environment.port')
DATABASE_URL=$(cat "$CONFIG_FILE" | jq -r '.environment.database_url')
REDIS_URL=$(cat "$CONFIG_FILE" | jq -r '.environment.redis_url')
FRONTEND_ORIGIN=$(cat "$CONFIG_FILE" | jq -r '.environment.frontend_origin')
JWT_SECRET=$(cat "$CONFIG_FILE" | jq -r '.environment.jwt_secret')

# Parse Redis URL
REDIS_HOST=$(echo "$REDIS_URL" | sed -n 's/redis:\/\/\([^:]*\).*/\1/p')
REDIS_PORT=$(echo "$REDIS_URL" | sed -n 's/redis:\/\/[^:]*:\([0-9]*\).*/\1/p')

# Backup existing .env if it exists
if [ -f ".env" ]; then
  BACKUP_FILE=".env.backup.$(date +%Y%m%d_%H%M%S)"
  cp .env "$BACKUP_FILE"
  echo "  ✓ Backed up existing .env to: $BACKUP_FILE"
fi

# Create new .env file
cat > .env <<EOF
# ============================================
# PRIMEFLOW ENVIRONMENT CONFIGURATION
# Generated by: scripts/setup-environment.sh
# Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# ============================================

# APPLICATION
NODE_ENV=production
PORT=$PORT
LOG_LEVEL=info

# FRONTEND
FRONTEND_ORIGIN=$FRONTEND_ORIGIN
VITE_APP_URL=$FRONTEND_ORIGIN

# DATABASE (Supabase PostgreSQL)
DATABASE_URL=$DATABASE_URL

# REDIS (for BullMQ queues)
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT

# AUTHENTICATION
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d

# SUPABASE (will be configured by Lovable Cloud)
VITE_SUPABASE_URL=https://spanwhewvcqsbpgwerck.supabase.co
VITE_SUPABASE_PUBLISHABLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwYW53aGV3dmNxc2JwZ3dlcmNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MTQyNTEsImV4cCI6MjA3NDk5MDI1MX0.HAAX0skJ2ulkq_pornAuXH2-3r2RyMH-vGt9XA_oMLY
VITE_SUPABASE_PROJECT_ID=spanwhewvcqsbpgwerck
SUPABASE_SERVICE_ROLE_KEY=\${SUPABASE_SERVICE_ROLE_KEY}

# LOVABLE AI (for AI features)
LOVABLE_API_KEY=\${LOVABLE_API_KEY}

# WHATSAPP (optional - configure if using WhatsApp integration)
WHATSAPP_PROVIDER=baileys
# FB_APP_ID=
# FB_APP_SECRET=

# INSTAGRAM (optional - configure if using Instagram integration)
# IG_APP_ID=
# IG_APP_SECRET=

# OPENAI (optional - for advanced AI features)
# OPENAI_API_KEY=

# STORAGE
STORAGE_DRIVER=supabase
UPLOADS_DIR=./uploads

# WORKER SETTINGS
WORKER_CONCURRENCY=10
WORKER_MAX_JOBS_PER_WORKER=100

EOF

echo "  ✓ Created new .env file"
echo ""

# Validate environment
echo "🔍 Validating environment..."

# Check if required variables are set
REQUIRED_VARS=("PORT" "DATABASE_URL" "JWT_SECRET" "REDIS_HOST")
MISSING_VARS=()

for var in "${REQUIRED_VARS[@]}"; do
  if ! grep -q "^${var}=" .env; then
    MISSING_VARS+=("$var")
    echo "  ✗ Missing: $var"
  else
    echo "  ✓ $var"
  fi
done

if [ ${#MISSING_VARS[@]} -gt 0 ]; then
  echo ""
  echo "⚠️  WARNING: ${#MISSING_VARS[@]} required variables are missing"
  echo "Please configure manually: ${MISSING_VARS[*]}"
  echo ""
fi

echo ""
echo "📋 Environment Summary:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Port: $PORT"
echo "  Database: ${DATABASE_URL:0:30}..."
echo "  Redis: $REDIS_HOST:$REDIS_PORT"
echo "  Frontend: $FRONTEND_ORIGIN"
echo "  JWT Secret: $(echo "$JWT_SECRET" | cut -c1-10)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ Environment configuration completed!"
echo ""
echo "📝 Next steps:"
echo "  1. Review .env file and configure optional services"
echo "  2. Set LOVABLE_API_KEY (will be provided by Lovable Cloud)"
echo "  3. Configure SUPABASE_SERVICE_ROLE_KEY if needed"
echo ""
